server:
    port: 9000
sshconfig:
    local-port: 8848
    mysql:
        remote-server: 10.100.101.79
    remote-port: 8848
    ssh:
        password: VsUn76@Atwasoft2020
        remote-port: 22
        remote-server: 10.98.1.10
        user: atwa
datasource:
    aggressiveLazyLoading: false
    callSettersOnNulls: true
    driver: oracle.jdbc.driver.OracleDriver
    initial-size: 5
    lazyLoadingEnabled: true
    max-active: 20
    password: sy_ptdx_kf
    pgpt:
        datasource-initialsize: 15
        datasource-logabandoned: true
        datasource-maxactive: 20
        datasource-maxwait: 1000
        datasource-querytimeout: 0
        datasource-removeabandoned: true
        datasource-removeabandonedtimeout: 180
        datasource-testonborrow: true
        datasource-validationquerySQL: 'select 1 '
        dbType: postgreSql
        jdbc-driver: org.postgresql.Driver
        jdbc-password: sy_ptdx
        jdbc-url: jdbc:postgresql://127.0.0.1:5432/sy_ptdx?currentSchema=sy_ptdx_1&stringtype=unspecified&useSSL=true
        jdbc-user: sy_ptdx
        state: true
    url: jdbc:oracle:thin:@113.125.201.130:15215/orcl
    username: sy_ptdx_kf
shineyue:
    db:
        datasources: oracl3;pgpt
    multiple:
        datasource:
            judgment:
                conditions: m-sy-service
